Repository IT-Cotato/10th-T-LINK-FE, pull requests merged in 2025-02, with the labels that each got.

#62 [Fix] 라우터 구조, 헤더 개선 및 초대 페이지를 모달 전용으로 변경
  src/components/Header.tsx
  src/components/NavBar.tsx
  src/components/RoomInfo.tsx
  src/pages/Invite.tsx
  src/pages/Room/CreateRoom.tsx
  src/pages/Room/RoomList.tsx
  src/pages/Room/ShareCode.tsx
  src/routes/Router.tsx
Labels: 🔨 Fix, 🌵 Refactor

#65 [Feat] 과외방 상세, 강의 자료함 UI
  package-lock.json
  package.json
  src/api/materials.api.ts
  src/assets/images/Add.svg
  src/assets/images/File_dock_add.svg
  src/assets/images/RoomDetail/Edit.svg
  src/assets/images/RoomDetail/counseling.svg
  src/assets/images/RoomDetail/homework.svg
  src/assets/images/RoomDetail/materials.svg
  src/assets/images/RoomDetail/statistics.svg
  src/assets/images/Search.svg
  src/assets/images/calendarGray.svg
  src/components/Button.tsx
  src/components/Calendar/CalendarDeposit.tsx
  src/components/Calendar/CalendarNolesson.tsx
  src/components/DetailButton.tsx
  src/components/Header.tsx
  src/components/LongButton.tsx
  src/components/NavBar.tsx
  src/components/Preview_1.tsx
  src/components/SearchBar.css
  src/components/SearchBar.tsx
  src/pages/Material/CreateMaterials.tsx
  src/pages/Material/Materials.tsx
  src/pages/Room/RoomDetail.tsx
  src/utils/formatDate.ts
Labels: ✨ Feat

#69 [Feat] 과외방 목록 axios 수정
  src/api/roomList.api.ts
  src/components/Calendar/CalendarGrid.tsx
  src/components/Calendar/CalendarNolesson.tsx
  src/components/Modal/InviteModal.tsx
  src/components/Modal/RoomDeleteModal.tsx
  src/components/Modal/ShareLinkModal.tsx
  src/components/RoomEditor.tsx
  src/components/RoomInfo.tsx
  src/models/room.model.ts
  src/pages/Room/CreateRoom.tsx
  src/pages/Room/EditRoom.tsx
  src/pages/Room/RoomList.tsx
  src/pages/Room/ShareCode.tsx
  src/utils/LessonDaysList.ts
Labels: ✨ Feat, 🔨 Fix

#71 [Fix] 회원가입 수정 및 공유코드 수정
  src/api/roomList.api.ts
  src/components/Modal/InviteModal.tsx
  src/models/user.model.ts
  src/pages/Invite.tsx
  src/pages/Room/RoomList.tsx
  src/pages/Signup/FormTel.tsx
  src/pages/Signup/Signup.tsx
  src/utils/RoleList.ts
Labels: 🔨 Fix

#79 [Fix] 과외방 초대 모달 수정 완료
  src/components/Modal/InviteModal.tsx
Labels: 🔨 Fix

#80 [Fix] lectureFiles -> lectureFile
  src/models/room.model.ts
  src/pages/Room/RoomDetail.tsx
Labels: 🔨 Fix

#86 [Fix] 카카오 url 모델 수정
  src/components/KakaoOauth.tsx
  src/models/user.model.ts
Labels: 🔨 Fix

#102 [Feat] 시험 및 성적 삭제 기능 구현 및 자잘한 수정
  src/api/statistics.api.ts
  src/components/Header.tsx
  src/components/Modal/CreateModal.tsx
  src/components/Modal/ProfileModal.tsx
  src/components/Modal/RoomDeleteModal.tsx
  src/components/Modal/ShareLinkModal.tsx
  src/components/RoomInfo.tsx
  src/components/Table.tsx
  src/pages/Statistics/CreateStatistics.tsx
Labels: ✨ Feat, 🔨 Fix
