Repository IT-Cotato/10th-T-LINK-FE, pull requests merged in 2025-01, with the labels that each got.

#47 [Feat] 상담 일지
  src/api/counseling.api.ts
  src/models/counseling.model.ts
  src/pages/Counseling/CounselingDetail.tsx
  src/pages/Counseling/CounselingDiary.tsx
  src/pages/Counseling/CreateCounseling.tsx
  src/routes/Router.tsx
Labels: Feat

#51 [Feat] 마이페이지 이용약관 및 탈퇴/로그아웃 모달
  eslint.config.js
  src/assets/images/Top Button.svg
  src/assets/images/term_button.svg
  src/components/Modal.tsx
  src/constants/termsOfService.tsx
  src/pages/MyPage.tsx
  src/pages/UserPolicy.tsx
  src/routes/Router.tsx
  tsconfig.app.json
Labels: Feat

#57 [Refactor] 모달 컴포넌트 분리, msw 비활성화, 불필요한 주석 및 console.log 삭제
  src/api/axios.ts
  src/components/Calendar/CalendarDeposit.tsx
  src/components/Calendar/CalendarGrid.tsx
  src/components/Calendar/CalendarInfo.tsx
  src/components/Calendar/CalendarLesson.tsx
  src/components/Calendar/CalendarNolesson.tsx
  src/components/Calendar/DateHandler.tsx
  src/components/Layout.tsx
  src/components/Modal/LogoutModal.tsx
  src/components/Modal/Modal.tsx
  src/components/Modal/ProfileModal.tsx
  src/components/Modal/StudentEditModal.tsx
  src/components/ProfileModal.tsx
  src/components/RoomInfo.tsx
  src/main.tsx
  src/pages/Calendar.tsx
  src/pages/MyPage.tsx
  src/pages/UserPolicy.tsx
Labels: 🌵 Refactor, 📂 Rename

#60 [Fix] 헤더 수정
  src/components/Header.tsx
  src/pages/UserPolicy.tsx
Labels: 🔨 Fix

#61 [Feat] 과외방 초대 링크 기능 구현
  src/components/DetailButton.tsx
  src/components/Modal/InviteModal.tsx
  src/components/Modal/ProfileModal.tsx
  src/components/Toast.tsx
  src/pages/Invite.tsx
  src/pages/Room/CreateRoom.tsx
  src/pages/Room/RoomDetail.tsx
  src/pages/Room/ShareCode.tsx
  src/routes/Router.tsx
Labels: ✨ Feat
